In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import time

In [2]:
df = pd.read_csv('/Users/ziadsamer/Documents/who-will-viral/data/youtube/youtube.csv')

/var/folders/p6/82pzwvfj08b5bktj5wbwqwh00000gn/T/ipykernel_12311/2405818914.py:1: DtypeWarning: Columns (0: trending_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/ziadsamer/Documents/who-will-viral/data/youtube/youtube.csv')

In [3]:
df.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,comment_count,thumbnail_link,comments_disabled,description,is_trending
0,G4M_621v1As,college farewell video#trending #viralshorts,2025-04-12T02:06:42Z,UC7k_7IF3s3TY-cowwxs_yWw,Vk_07_rider,22.0,2025-11-08,"college farewell video, DDU farewell video, fa...",125784084.0,1557178.0,1583.0,https://i.ytimg.com/vi/G4M_621v1As/default.jpg,0,DDU farewell party video \n college farewell v...,1
1,z2voqo_Jhx4,Busking in Manchester 🇬🇧 #blindfaith #guitar #...,2025-04-06T11:35:53Z,UCM_9JHB3xXPSzJfTkD86AtA,Leonardo Patrick,10.0,2025-11-08,NaN,94744011.0,925529.0,5849.0,https://i.ytimg.com/vi/z2voqo_Jhx4/default.jpg,0,NaN,1
2,jHIt9oHFLsw,This is what happens when you play Star Wars i...,2025-04-06T10:07:12Z,UC4YyKY5o60Kckk-GXOnhT2g,Violin Phonix,22.0,2025-11-08,NaN,61945818.0,1067412.0,4124.0,https://i.ytimg.com/vi/jHIt9oHFLsw/default.jpg,0,Full video : https://www.youtube.com/watch?v=Q...,1
3,gwRqLbWqKlM,LISA - FUTW (YouTube Music Nights Special Stag...,2025-03-19T03:29:33Z,UC6-BgjsBa5R3PZQ_kZ8hKPg,LLOUD Official,10.0,2025-11-08,"Blackpink, Lisa, Music, Fashion, K-Pop, kpop, ...",14555963.0,455816.0,20396.0,https://i.ytimg.com/vi/gwRqLbWqKlM/default.jpg,0,"LISA’s debut album, ‘Alter Ego’ is out now. Li...",1
4,prpRoyrutcE,Uljhi hai yeh kis jaal me tu…. Bengaluru ❤️,2025-04-14T10:17:58Z,UCiFXnvi8ESDukE25ol2foWQ,Mr.KiranJ,10.0,2025-11-08,NaN,26204942.0,336267.0,2333.0,https://i.ytimg.com/vi/prpRoyrutcE/default.jpg,0,NaN,1

In [4]:
df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'comments_disabled', 'description',
       'is_trending'],
      dtype='str')

In [5]:
# all False has missing trending_date
df[df['is_trending'] == False]['trending_date'].isnull().sum() / df[df['is_trending'] == False]['trending_date'].shape[0]

np.float64(1.0)

## API result

```json
{
  'kind': 'youtube#searchResult',
  'etag': 'dK1WzM52BCYZOt3H87hwS1TAptg',
  'id': {'kind': 'youtube#video', 'videoId': 's2OccJMWwkM'},
  'snippet': {'publishedAt': '2025-10-09T11:17:36Z',
    'channelId': 'UCMiJRAwDNSNzuYeN2uWa0pA',
    'title': 'REAL vs FAKE Tech',
    'description': 'The fakes were a LOT better than I expected Get the Insta360 GO Ultra: the best POV vlogging cam: ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/default.jpg',
      'width': 120,
      'height': 90},
    'medium': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/mqdefault.jpg',
      'width': 320,
      'height': 180},
    'high': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Mrwhosetheboss',
    'liveBroadcastContent': 'none',
  'publishTime': '2025-10-09T11:17:36Z'}
}
  ```

```json
{
    'kind': 'youtube#video',
    'etag': 'E0nj7zS5ZHov09YCnA9Suh4frG4',
    'id': 's2OccJMWwkM',
    'snippet': {'publishedAt': '2025-10-09T11:17:36Z',
    'channelId': 'UCMiJRAwDNSNzuYeN2uWa0pA',
    'title': 'REAL vs FAKE Tech',
    'description': "The fakes were a LOT better than I expected \nGet the Insta360 GO Ultra: the best POV vlogging cam: https://bit.ly/Mrwhosetheboss-Insta360GOUltra. First 30 orders get an exclusive 256GB SD Card! \n- Tiny & Lightweight & Portable (just 53g)\n- Hands-Free POV + Wide FOV\n- Magic Magnetic Mounting\n- Upgraded Image: 1/1.28” Sensor + 5nm AI Chip\n- Long Battery Life: 60min @4K30 standalone; 170min @4K30 with Action Pod\n#Insta360GOUltra #pocketcamera #vloggingcamera\n\nI spend a LOT of time trying to make my videos as concise, polished and useful as possible for you - if you would like to support me on that mission then consider subscribing to the channel - you'd make my day 😁\n\nFor my tech hot takes: http://twitter.com/Mrwhosetheboss\nFor my Personal Posts: http://instagram.com/mrwhosetheboss\nFor quick tech videos: https://www.tiktok.com/@mrwhosetheboss\nDoes anyone still use this anymore?: https://facebook.com/mrwhosetheboss\n\nAmazon Affiliate links (if you buy anything through these it will support the channel and allow us to buy better gear!):\nAmazon US: https://amzn.to/3mFix9d\nAmazon UK: https://amzn.to/3GMPPtM\n\nMy Browser: https://opr.as/Opera-browser-Mr-Whose-the-Boss \nMy Filming Gear: https://bit.ly/35CuxwI\n\nMusic is from Epidemic sound:\nhttp://share.epidemicsound.com/pHDFT",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/default.jpg',
      'width': 120,
      'height': 90},
    'medium': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/mqdefault.jpg',
      'width': 320,
      'height': 180},
    'high': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/hqdefault.jpg',
      'width': 480,
      'height': 360},
    'standard': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/sddefault.jpg',
      'width': 640,
      'height': 480},
    'maxres': {'url': 'https://i.ytimg.com/vi/s2OccJMWwkM/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'Mrwhosetheboss',
    'tags': ['real', 'fake', 'tech', 'apple', 'philips hue', 'govee', 'gifts', 'gadgets'],
    'categoryId': '28',
    'liveBroadcastContent': 'none',
    'defaultLanguage': 'en',
    'localized': {'title': 'REAL vs FAKE Tech',
    'description': "The fakes were a LOT better than I expected \nGet the Insta360 GO Ultra: the best POV vlogging cam: https://bit.ly/Mrwhosetheboss-Insta360GOUltra. First 30 orders get an exclusive 256GB SD Card! \n- Tiny & Lightweight & Portable (just 53g)\n- Hands-Free POV + Wide FOV\n- Magic Magnetic Mounting\n- Upgraded Image: 1/1.28” Sensor + 5nm AI Chip\n- Long Battery Life: 60min @4K30 standalone; 170min @4K30 with Action Pod\n#Insta360GOUltra #pocketcamera #vloggingcamera\n\nI spend a LOT of time trying to make my videos as concise, polished and useful as possible for you - if you would like to support me on that mission then consider subscribing to the channel - you'd make my day 😁\n\nFor my tech hot takes: http://twitter.com/Mrwhosetheboss\nFor my Personal Posts: http://instagram.com/mrwhosetheboss\nFor quick tech videos: https://www.tiktok.com/@mrwhosetheboss\nDoes anyone still use this anymore?: https://facebook.com/mrwhosetheboss\n\nAmazon Affiliate links (if you buy anything through these it will support the channel and allow us to buy better gear!):\nAmazon US: https://amzn.to/3mFix9d\nAmazon UK: https://amzn.to/3GMPPtM\n\nMy Browser: https://opr.as/Opera-browser-Mr-Whose-the-Boss \nMy Filming Gear: https://bit.ly/35CuxwI\n\nMusic is from Epidemic sound:\nhttp://share.epidemicsound.com/pHDFT"},
    'defaultAudioLanguage': 'en-GB'},
  'contentDetails': {'duration': 'PT22M46S',
    'dimension': '2d',
    'definition': 'hd',
    'caption': 'false',
    'licensedContent': True,
    'contentRating': {},
    'projection': 'rectangular'},
  'statistics': {'viewCount': '12532806',
    'likeCount': '223339',
    'favoriteCount': '0',
    'commentCount': '6127'}
}
```

# API

In [6]:
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("YOUTUBE_KEY")

In [7]:
from googleapiclient.discovery import build

In [8]:
youtube = build("youtube", "v3", developerKey=api_key)

In [9]:
# video_id
# trending_date,thumbnail_link,comments_disabled,
# is_trending

In [10]:
def get_video_details(video_ids):
    stats_request = youtube.videos().list(
        part="statistics,contentDetails,snippet,status",
        id=",".join(video_ids),
        fields='items(id,snippet(defaultLanguage),\
            statistics(favoriteCount),status(embeddable,madeForKids),\
            contentDetails(duration,dimension,definition,caption,\
                licensedContent,contentRating,projection,regionRestriction))'
    )

    response = stats_request.execute()
    return response['items']

In [11]:
all_ids = df['video_id'].unique().tolist()

In [12]:
len(all_ids) / len(df)

0.4867847903949052

In [13]:
all_ids[0]

'G4M_621v1As'

In [14]:
# videos_data = []
# for i in tqdm(range(0, len(all_ids), 50)):
#     batch_ids = all_ids[i:i+50]
#     details = get_video_details(batch_ids)
#     videos_data.append(details)
#     time.sleep(0.01)  # To respect API rate limits

In [15]:
# videos_flattened = [item for sublist in videos_data for item in sublist]

In [16]:
import json
# with open('youtube_api_backup.json', 'w') as file:
#     json.dump(videos_flattened, file, indent=4)

In [17]:
df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'comments_disabled', 'description',
       'is_trending'],
      dtype='str')

In [18]:
with open('youtube_api_backup.json', 'r') as file:
    videos_flattened = json.load(file)

In [19]:
videos_flattened[0]

{'id': 'G4M_621v1As',
 'snippet': {'defaultLanguage': 'en'},
 'contentDetails': {'duration': 'PT15S',
  'dimension': '2d',
  'definition': 'hd',
  'caption': 'false',
  'licensedContent': False,
  'contentRating': {},
  'projection': 'rectangular'},
 'status': {'embeddable': True, 'madeForKids': False},
 'statistics': {'favoriteCount': '0'}}

In [20]:
to_add = {
    'id' : [],
    'defaultLanguage' : [],
    'favoriteCount' : [],
    'embeddable' : [],
    'madeForKids' : [],
    'duration' : [],
    'dimension' : [],
    'definition' : [],
    'caption' : [],
    'licensedContent' : [],
    'contentRating' : [],
    'projection' : [],
    'regionRestriction' : []
}
for i, flattened in enumerate(videos_flattened):
    for key, value in flattened.items():
        if isinstance(value, dict):
            for subkey, subvalue in value.items():
                to_add[subkey.split('.')[-1]].append(subvalue)
        else:
            to_add[key].append(value)

In [21]:
for key in to_add.keys():
    print(key, len(to_add[key]))

id 182395
defaultLanguage 182395
favoriteCount 182395
embeddable 182395
madeForKids 182395
duration 182392
dimension 182395
definition 182395
caption 182395
licensedContent 182395
contentRating 182395
projection 182395
regionRestriction 12950

In [22]:
to_add.keys()

dict_keys(['id', 'defaultLanguage', 'favoriteCount', 'embeddable', 'madeForKids', 'duration', 'dimension', 'definition', 'caption', 'licensedContent', 'contentRating', 'projection', 'regionRestriction'])

In [23]:
online_df = pd.json_normalize(videos_flattened)
online_df.head()

,id,snippet.defaultLanguage,contentDetails.duration,contentDetails.dimension,contentDetails.definition,contentDetails.caption,contentDetails.licensedContent,contentDetails.projection,status.embeddable,status.madeForKids,statistics.favoriteCount,contentDetails.regionRestriction.blocked,contentDetails.regionRestriction.allowed,contentDetails.contentRating.ytRating
0,G4M_621v1As,en,PT15S,2d,hd,false,False,rectangular,True,False,0,NaN,NaN,NaN
1,z2voqo_Jhx4,en,PT30S,2d,hd,false,True,rectangular,True,False,0,NaN,NaN,NaN
2,jHIt9oHFLsw,en,PT1M,2d,hd,false,True,rectangular,True,False,0,NaN,NaN,NaN
3,gwRqLbWqKlM,en,PT2M56S,2d,hd,false,False,rectangular,True,False,0,[RU],NaN,NaN
4,prpRoyrutcE,en,PT1M1S,2d,hd,false,True,rectangular,True,False,0,NaN,NaN,NaN

In [24]:
online_df.isnull().sum()

id                                               0
snippet.defaultLanguage                          0
contentDetails.duration                          3
contentDetails.dimension                         0
contentDetails.definition                        0
contentDetails.caption                           0
contentDetails.licensedContent                   0
contentDetails.projection                        0
status.embeddable                                0
status.madeForKids                               0
statistics.favoriteCount                         0
contentDetails.regionRestriction.blocked    173046
contentDetails.regionRestriction.allowed    178794
contentDetails.contentRating.ytRating       182142
dtype: int64

In [25]:
columns = [col.split('.')[1] if '.' in col and len(col.split('.')) == 2 else col for col in online_df.columns]

In [26]:
online_df.columns = columns

In [27]:
online_df.columns

Index(['id', 'defaultLanguage', 'duration', 'dimension', 'definition',
       'caption', 'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'contentDetails.regionRestriction.blocked',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.contentRating.ytRating'],
      dtype='str')

In [68]:
big_df = df.merge(online_df, left_on='video_id', right_on='id', how='left')

In [69]:
big_df.drop(columns=['id'], inplace=True)

In [70]:
len(big_df) / len(df)

1.0

In [71]:
big_df.isnull().sum()

video_id                                         0
title                                            0
publishedAt                                      0
channelId                                        0
channelTitle                                     0
categoryId                                       0
trending_date                               218362
tags                                        120820
view_count                                       0
likes                                            0
comment_count                                    0
thumbnail_link                                   0
comments_disabled                                0
description                                  59300
is_trending                                      0
defaultLanguage                              15182
duration                                     15190
dimension                                    15182
definition                                   15182
caption                                      15182
licensedContent                              15182
projection                                   15182
embeddable                                   15182
madeForKids                                  15182
favoriteCount                                15182
contentDetails.regionRestriction.blocked    371041
contentDetails.regionRestriction.allowed    375855
contentDetails.contentRating.ytRating       389538
dtype: int64

## Get Trending

In [74]:
online_df.columns

Index(['id', 'defaultLanguage', 'duration', 'dimension', 'definition',
       'caption', 'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'contentDetails.regionRestriction.blocked',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.contentRating.ytRating'],
      dtype='str')

In [75]:
big_df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'comments_disabled', 'description',
       'is_trending', 'defaultLanguage', 'duration', 'dimension', 'definition',
       'caption', 'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'contentDetails.regionRestriction.blocked',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.contentRating.ytRating'],
      dtype='str')

In [38]:
big_df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'comments_disabled', 'description',
       'is_trending', 'defaultLanguage', 'duration', 'dimension', 'definition',
       'caption', 'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'regionRestriction', 'regionRestriction',
       'contentRating'],
      dtype='str')

In [77]:
def get_trending_videos():
    stats_request = youtube.videos().list(
        part="statistics,contentDetails,snippet,status",
        chart='mostPopular',
        maxResults=1000,
        fields='items(id,snippet(title,publishedAt,channelId,title,description,channelTitle,\
            tags,defaultLanguage,categoryId,thumbnails),\
            statistics(viewCount, favoriteCount, commentCount, likeCount),status(embeddable,madeForKids),\
            contentDetails(duration,dimension,definition,caption,\
                licensedContent,contentRating,projection,caption,regionRestriction))'
    )

    response = stats_request.execute()
    return response['items']

In [78]:
# def get_comments_disabled(video_ids):
#     stats_request = youtube.commentThreads().list(
#         part="id",
#         id=",".join(video_ids)
#     )

#     response = stats_request.execute()
#     return response['items']

In [80]:
trending_videos = get_trending_videos()

In [ ]:
# with open('trending_videos_backup.json', 'w') as file:
#     json.dump(trending_videos, file, indent=4)
# with open('trending_videos_backup.json', 'r') as file:
#     trending_videos = json.load(file)

In [225]:
trending_videos[0]

{'id': '4EUyOMwPcQ0',
 'snippet': {'publishedAt': '2026-04-05T08:00:00Z',
  'channelId': 'UCLkAepWjdylmXSltofFvsYQ',
  'title': "BTS '2.0' MV Behind the Scenes",
  'description': '#BTS #방탄소년단 #BTS_ARIRANG #2point0 \n\nConnect with BTS:\nhttps://ibighit.com/bts\nhttps://x.com/bts_bighit\nhttps://x.com/BTS_twt\nhttp://www.facebook.com/bangtan.official\nhttps://www.youtube.com/user/BANGTANTV\nhttp://instagram.com/BTS.bighitofficial\nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.io/bts/highlight\nhttps://www.weibo.com/BTSbighit',
  'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/default.jpg',
    'width': 120,
    'height': 90},
   'medium': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/mqdefault.jpg',
    'width': 320,
    'height': 180},
   'high': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/hqdefault.jpg',
    'width': 480,
    'height': 360},
   'standard': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/sddefault.jpg',
    'width': 640,
    'height': 480},
   'maxres': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/maxresdefault.jpg',
    'width': 1280,
    'height': 720}},
  'channelTitle': 'BANGTANTV',
  'tags': ['방탄소년단',
   'BTS',
   'BANGTAN',
   '알엠',
   'RM',
   '슈가',
   'SUGA',
   '제이홉',
   'jhope',
   '지민',
   '정국',
   'k-pop',
   '방탄',
   'j-hope',
   'Jung Kook',
   'Jimin',
   'BTS V',
   'Jin'],
  'categoryId': '10',
  'defaultLanguage': 'ko'},
 'contentDetails': {'duration': 'PT7M32S',
  'dimension': '2d',
  'definition': 'hd',
  'caption': 'true',
  'licensedContent': True,
  'contentRating': {},
  'projection': 'rectangular'},
 'status': {'embeddable': True, 'madeForKids': False},
 'statistics': {'viewCount': '1615900',
  'likeCount': '305022',
  'favoriteCount': '0',
  'commentCount': '11096'}}

In [83]:
trending_videos_copy = trending_videos.copy()

In [226]:
for video in trending_videos:   
    video['thumbnail_link'] = video['snippet']['thumbnails']['default']['url']

In [227]:
trending_videos[0]

{'id': '4EUyOMwPcQ0',
 'snippet': {'publishedAt': '2026-04-05T08:00:00Z',
  'channelId': 'UCLkAepWjdylmXSltofFvsYQ',
  'title': "BTS '2.0' MV Behind the Scenes",
  'description': '#BTS #방탄소년단 #BTS_ARIRANG #2point0 \n\nConnect with BTS:\nhttps://ibighit.com/bts\nhttps://x.com/bts_bighit\nhttps://x.com/BTS_twt\nhttp://www.facebook.com/bangtan.official\nhttps://www.youtube.com/user/BANGTANTV\nhttp://instagram.com/BTS.bighitofficial\nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.io/bts/highlight\nhttps://www.weibo.com/BTSbighit',
  'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/default.jpg',
    'width': 120,
    'height': 90},
   'medium': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/mqdefault.jpg',
    'width': 320,
    'height': 180},
   'high': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/hqdefault.jpg',
    'width': 480,
    'height': 360},
   'standard': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/sddefault.jpg',
    'width': 640,
    'height': 480},
   'maxres': {'url': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/maxresdefault.jpg',
    'width': 1280,
    'height': 720}},
  'channelTitle': 'BANGTANTV',
  'tags': ['방탄소년단',
   'BTS',
   'BANGTAN',
   '알엠',
   'RM',
   '슈가',
   'SUGA',
   '제이홉',
   'jhope',
   '지민',
   '정국',
   'k-pop',
   '방탄',
   'j-hope',
   'Jung Kook',
   'Jimin',
   'BTS V',
   'Jin'],
  'categoryId': '10',
  'defaultLanguage': 'ko'},
 'contentDetails': {'duration': 'PT7M32S',
  'dimension': '2d',
  'definition': 'hd',
  'caption': 'true',
  'licensedContent': True,
  'contentRating': {},
  'projection': 'rectangular'},
 'status': {'embeddable': True, 'madeForKids': False},
 'statistics': {'viewCount': '1615900',
  'likeCount': '305022',
  'favoriteCount': '0',
  'commentCount': '11096'},
 'thumbnail_link': 'https://i.ytimg.com/vi/4EUyOMwPcQ0/default.jpg'}

In [228]:
trending_df = pd.json_normalize(trending_videos)

In [230]:
cols_to_drop = [col for col in trending_df.columns if 'thumbnails' in col]
trending_df.drop(columns=cols_to_drop, inplace=True)

In [231]:
len(big_df.columns), len(trending_df.columns)

(28, 24)

In [232]:
len(trending_df.columns)

24

In [233]:
# The if/else goes first,  the for loop
columns = [col.split('.')[1] if '.' in col and len(col.split('.')) == 2 else col for col in trending_df.columns]
trending_df.columns = columns

In [234]:
big_df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'comments_disabled', 'description',
       'is_trending', 'defaultLanguage', 'duration', 'dimension', 'definition',
       'caption', 'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'contentDetails.regionRestriction.blocked',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.contentRating.ytRating'],
      dtype='str')

In [235]:
trending_df.columns 
# add contentDetails.contentRating.ytRating = NaN
# is_trending = True
# trending_date = today's date
# comments_disabled = NaN

Index(['id', 'thumbnail_link', 'publishedAt', 'channelId', 'title',
       'description', 'channelTitle', 'tags', 'categoryId', 'defaultLanguage',
       'duration', 'dimension', 'definition', 'caption', 'licensedContent',
       'projection', 'embeddable', 'madeForKids', 'viewCount', 'likeCount',
       'favoriteCount', 'commentCount',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.regionRestriction.blocked'],
      dtype='str')

In [236]:
for column in big_df.columns:
    if column not in trending_df.columns and column not in ['is_trending', 'trending_date']:
        print(column)

video_id
view_count
likes
comment_count
comments_disabled
contentDetails.contentRating.ytRating

In [237]:
trending_df['is_trending'] = True
trending_df['trending_date'] = pd.to_datetime('today').strftime('%Y-%m-%d')
trending_df['comments_disabled'] = np.nan

In [238]:
trending_df.rename(columns={'id': 'video_id', 
                            'likeCount': 'likes', 
                            'viewCount': 'view_count', 
                            'commentCount': 'comment_count'}, inplace=True)

In [239]:
for column in big_df.columns:
    if column not in trending_df.columns:
        trending_df[column] = np.nan

In [240]:
assert set(big_df.columns) == set(trending_df.columns)

In [241]:
trending_df.head()

,video_id,thumbnail_link,publishedAt,channelId,title,description,channelTitle,tags,categoryId,defaultLanguage,...,view_count,likes,favoriteCount,comment_count,contentDetails.regionRestriction.allowed,contentDetails.regionRestriction.blocked,is_trending,trending_date,comments_disabled,contentDetails.contentRating.ytRating
0,4EUyOMwPcQ0,https://i.ytimg.com/vi/4EUyOMwPcQ0/default.jpg,2026-04-05T08:00:00Z,UCLkAepWjdylmXSltofFvsYQ,BTS '2.0' MV Behind the Scenes,#BTS #방탄소년단 #BTS_ARIRANG #2point0 \n\nConnect ...,BANGTANTV,"[방탄소년단, BTS, BANGTAN, 알엠, RM, 슈가, SUGA, 제이홉, j...",10,ko,...,1615900,305022,0,11096,NaN,NaN,True,2026-04-05,NaN,NaN
1,i3JXHVqWu1A,https://i.ytimg.com/vi/i3JXHVqWu1A/default.jpg,2026-04-05T13:01:26Z,UCD9-oAYJYLAX5GAKCz_48SA,NCAAM Final Four: Michigan vs. Arizona,The Wolverines play the Wildcats in the Final ...,TBS,NaN,24,en,...,NaN,NaN,0,NaN,NaN,NaN,True,2026-04-05,NaN,NaN
2,ljyno2XoRyc,https://i.ytimg.com/vi/ljyno2XoRyc/default.jpg,2026-04-05T11:01:15Z,UCqZWmpmj24iC7dletjnf_gA,"He Is Risen! Easter Worship 2026, Best Christi...","He Is Risen! Easter Worship 2026, Best Christi...",Worship Songs,"[He Is Risen!, Easter Worship 2026, Best Chris...",10,en,...,31724,476,0,20,NaN,NaN,True,2026-04-05,NaN,NaN
3,VrBc93776cQ,https://i.ytimg.com/vi/VrBc93776cQ/default.jpg,2026-04-05T18:36:59Z,UCqWYIzQLZFW4NFXPfWBLW1w,Fox & Friends Weekend,"FOX & Friends Weekend, hosted by Rachel Campos...",FOX News,NaN,24,en,...,NaN,NaN,0,NaN,NaN,NaN,True,2026-04-05,NaN,NaN
4,YqXmiZZVtD0,https://i.ytimg.com/vi/YqXmiZZVtD0/default.jpg,2026-04-02T14:00:06Z,UCACfJmh_OB_IcVxtZQoGYKQ,Oh girl - Tonton Malele (feat. Sean Rii),Business Enquiries: maimaiincpg@gmail.com\n\nC...,Tonton Malele,NaN,10,en,...,41147,2381,0,240,NaN,NaN,True,2026-04-05,NaN,NaN

In [242]:
trending_df.to_csv('/Users/ziadsamer/Documents/who-will-viral/data/youtube/trending_videos.csv', index=False)

# Get Non-Trending

In [164]:
from datetime import datetime, timedelta

def get_random_videos(genre=None):
    published_after = (datetime.utcnow() - timedelta(days=1)).isoformat("T") + "Z"

    request = youtube.search().list(
        part="snippet",
        type="video",
        maxResults=50,
        order="date",  # or "relevance"
        publishedAfter=published_after,
        q=genre if genre else '',  # Optional: filter by genre
        fields='items(id,snippet(title,publishedAt,channelId,title,description,channelTitle,\
            thumbnails))'

    )

    response = request.execute()
    return response["items"]

In [165]:
genres = ["cooking" ,"AI", "coding", "history", "gym" ,"speed", "vlog", "challenge", "reaction", "music", "gaming", "education", "comedy", "news", "sports", "beauty", "entertainment", "nonprofits", "howto", "science", "nonprofits", "howto", "science", "nonprofits", "howto", "science"]
genres = list(set(genres))

In [166]:
non_trending_videos = []
for i in tqdm(genres):
    videos = get_random_videos(genre=i)
    non_trending_videos.extend(videos)
    time.sleep(0.01)  # To respect API rate limits

  0%|          | 0/20 [00:00<?, ?it/s]/var/folders/p6/82pzwvfj08b5bktj5wbwqwh00000gn/T/ipykernel_22437/3373707131.py:4: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  published_after = (datetime.utcnow() - timedelta(days=1)).isoformat("T") + "Z"
100%|██████████| 20/20 [00:08<00:00,  2.39it/s]

In [167]:
all_non_trending_ids = [video['id']['videoId'] for video in non_trending_videos]

In [168]:
with open('non_trending_videos_backup.json', 'w') as file:
    json.dump(non_trending_videos, file, indent=4)

In [169]:
def get_non_trending_video_details(video_ids):
    stats_request = youtube.videos().list(
        part="statistics,contentDetails,snippet,status",
        id=",".join(video_ids),
        fields='items(id,snippet(title,publishedAt,channelId,title,description,channelTitle,\
            tags,defaultLanguage,categoryId,thumbnails),\
            statistics(viewCount, favoriteCount, commentCount, likeCount),status(embeddable,madeForKids),\
            contentDetails(duration,dimension,definition,caption,\
                licensedContent,contentRating,projection,caption,regionRestriction))'
    )

    response = stats_request.execute()
    return response['items']

In [157]:
# def get_trending_videos():
#     stats_request = youtube.videos().list(
#         part="statistics,contentDetails,snippet,status",
#         chart='mostPopular',
#         maxResults=1000,
#         fields='items(id,snippet(title,publishedAt,channelId,title,description,channelTitle,\
#             tags,defaultLanguage,categoryId,thumbnails),\
#             statistics(viewCount, favoriteCount, commentCount, likeCount),status(embeddable,madeForKids),\
#             contentDetails(duration,dimension,definition,caption,\
#                 licensedContent,contentRating,projection,caption,regionRestriction))'
#     )

#     response = stats_request.execute()
#     return response['items']

In [194]:
new_nono_trending_ids = [id if id not in trending_df['video_id'].tolist() and id not in big_df['video_id'].tolist() else None for id in all_non_trending_ids]

In [195]:
new_non_trending_ids = [id for id in new_nono_trending_ids if id is not None]

In [ ]:
videos_data = []
for i in tqdm(range(0, len(new_non_trending_ids), 50)):
    batch_ids = new_non_trending_ids[i:i+50]
    details = get_non_trending_video_details(batch_ids)
    videos_data.append(details)
    time.sleep(0.01)  # To respect API rate limits

100%|██████████| 20/20 [00:05<00:00,  3.53it/s]

In [171]:
videos_flattened = [item for sublist in videos_data for item in sublist]

In [172]:
len(videos_flattened)

964

In [ ]:
# with open('non_trending_videos_backup_flattened.json', 'w') as file:
#     json.dump(videos_flattened, file, indent=4)
# with open('non_trending_videos_backup_flattened.json', 'r') as file:
#     videos_flattened = json.load(file)

In [209]:
trending_df.columns

Index(['video_id', 'thumbnail_link', 'publishedAt', 'channelId', 'title',
       'description', 'channelTitle', 'tags', 'categoryId', 'defaultLanguage',
       'duration', 'dimension', 'definition', 'caption', 'licensedContent',
       'projection', 'embeddable', 'madeForKids', 'view_count', 'likes',
       'favoriteCount', 'comment_count',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.regionRestriction.blocked', 'is_trending',
       'trending_date', 'comments_disabled',
       'contentDetails.contentRating.ytRating'],
      dtype='str')

In [210]:
nonotrend_online_df = pd.json_normalize(videos_flattened)
nonotrend_online_df.head()

,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,snippet.thumbnails.medium.url,snippet.thumbnails.medium.width,...,contentDetails.projection,status.embeddable,status.madeForKids,statistics.viewCount,statistics.likeCount,statistics.favoriteCount,statistics.commentCount,contentDetails.regionRestriction.blocked,snippet.tags,contentDetails.regionRestriction.allowed
0,-grbtTNw0vQ,2026-04-05T18:47:01Z,UCYeQ03iVfPjjBM-ypSMP--w,ప్రణామం #shortsfeed #trending #youtubeshorts ...,ప్రణామం #shortsfeed #trending #youtubeshorts ...,https://i.ytimg.com/vi/-grbtTNw0vQ/default.jpg,120,90,https://i.ytimg.com/vi/-grbtTNw0vQ/mqdefault.jpg,320,...,rectangular,True,False,600,13,0,0,NaN,NaN,NaN
1,EAXbAYXZtBI,2026-04-05T18:35:00Z,UCWmoxoc0ZAADAs88g-BsJZw,🔥🔥🔥🔥🔥#loki #entertainment #dance #tomhiddlest...,,https://i.ytimg.com/vi/EAXbAYXZtBI/default.jpg,120,90,https://i.ytimg.com/vi/EAXbAYXZtBI/mqdefault.jpg,320,...,rectangular,True,False,924,48,0,0,[RU],NaN,NaN
2,PO53irSj9Xw,2026-04-05T18:15:04Z,UCYL8IUjoaiaRTuuLWhzwoyw,Wife ko aise kaun mna karta hai 🤣🤣 #comedy #fu...,Pati ne kiya wife ko mna shopping ke liye. \n\...,https://i.ytimg.com/vi/PO53irSj9Xw/default.jpg,120,90,https://i.ytimg.com/vi/PO53irSj9Xw/mqdefault.jpg,320,...,rectangular,True,False,1951,1,0,0,NaN,"[Comedy, Comedy short, Comedy video, Funny, Fu...",NaN
3,Zx8AqGGCAvA,2026-04-05T17:44:35Z,UCdJnb9jD5z7FuOdNHUgzRSw,kese banii tina ek IAS officer🫡. #viral #expl...,kese banii tina ek IAS officer🫡. #viral #expl...,https://i.ytimg.com/vi/Zx8AqGGCAvA/default.jpg,120,90,https://i.ytimg.com/vi/Zx8AqGGCAvA/mqdefault.jpg,320,...,rectangular,True,False,1370,NaN,0,0,NaN,"[viral, trending, ias, villege stories, motiva...",NaN
4,WemuVva-BPA,2026-04-05T17:43:18Z,UCDBNhShEGgEvTpJKqTa4L2Q,#funny #entertainment #comedyshorts 😭😭,entertainment shots 😍 comedy shorts subscribe ...,https://i.ytimg.com/vi/WemuVva-BPA/default.jpg,120,90,https://i.ytimg.com/vi/WemuVva-BPA/mqdefault.jpg,320,...,rectangular,True,False,843,6,0,0,NaN,[entertainment shots 😍 comedy shorts subscribe...,NaN

In [211]:
new_columns = []
nontrend_cols = nonotrend_online_df.columns
cols_to_drop = []
for col in nontrend_cols:
    if col == 'snippet.thumbnails.default.url':
        new_columns.append('thumbnail_link')
    elif 'thumbnails' in col:
        cols_to_drop.append(col)
    elif '.' in col and len(col.split('.')) == 2:
        new_columns.append(col.split('.')[1])
    else:
        new_columns.append(col)

In [212]:
nonotrend_online_df.drop(columns=cols_to_drop, inplace=True)

In [214]:
assert len(nonotrend_online_df.columns) == len(new_columns)

In [215]:
nonotrend_online_df.columns = new_columns

In [216]:
nonotrend_online_df['is_trending'] = False
nonotrend_online_df['trending_date'] = pd.to_datetime('today').strftime('%Y-%m-%d')
nonotrend_online_df['comments_disabled'] = np.nan

nonotrend_online_df.rename(columns={'id': 'video_id', 
                            'likeCount': 'likes', 
                            'viewCount': 'view_count', 
                            'commentCount': 'comment_count'}, inplace=True)

for column in big_df.columns:
    if column not in nonotrend_online_df.columns:
        nonotrend_online_df[column] = np.nan

In [217]:
assert len(nonotrend_online_df.columns) == len(trending_df.columns) == len(big_df.columns)

# Combine All !!!

In [243]:
final_df = pd.concat([big_df, trending_df, nonotrend_online_df], ignore_index=True)
final_df.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,...,definition,caption,licensedContent,projection,embeddable,madeForKids,favoriteCount,contentDetails.regionRestriction.blocked,contentDetails.regionRestriction.allowed,contentDetails.contentRating.ytRating
0,G4M_621v1As,college farewell video#trending #viralshorts,2025-04-12T02:06:42Z,UC7k_7IF3s3TY-cowwxs_yWw,Vk_07_rider,22.0,2025-11-08,"college farewell video, DDU farewell video, fa...",125784084.0,1557178.0,...,hd,false,False,rectangular,True,False,0,NaN,NaN,NaN
1,z2voqo_Jhx4,Busking in Manchester 🇬🇧 #blindfaith #guitar #...,2025-04-06T11:35:53Z,UCM_9JHB3xXPSzJfTkD86AtA,Leonardo Patrick,10.0,2025-11-08,NaN,94744011.0,925529.0,...,hd,false,True,rectangular,True,False,0,NaN,NaN,NaN
2,jHIt9oHFLsw,This is what happens when you play Star Wars i...,2025-04-06T10:07:12Z,UC4YyKY5o60Kckk-GXOnhT2g,Violin Phonix,22.0,2025-11-08,NaN,61945818.0,1067412.0,...,hd,false,True,rectangular,True,False,0,NaN,NaN,NaN
3,gwRqLbWqKlM,LISA - FUTW (YouTube Music Nights Special Stag...,2025-03-19T03:29:33Z,UC6-BgjsBa5R3PZQ_kZ8hKPg,LLOUD Official,10.0,2025-11-08,"Blackpink, Lisa, Music, Fashion, K-Pop, kpop, ...",14555963.0,455816.0,...,hd,false,False,rectangular,True,False,0,[RU],NaN,NaN
4,prpRoyrutcE,Uljhi hai yeh kis jaal me tu…. Bengaluru ❤️,2025-04-14T10:17:58Z,UCiFXnvi8ESDukE25ol2foWQ,Mr.KiranJ,10.0,2025-11-08,NaN,26204942.0,336267.0,...,hd,false,True,rectangular,True,False,0,NaN,NaN,NaN

In [244]:
final_df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'comments_disabled', 'description',
       'is_trending', 'defaultLanguage', 'duration', 'dimension', 'definition',
       'caption', 'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'contentDetails.regionRestriction.blocked',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.contentRating.ytRating'],
      dtype='str')

In [245]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 391057 entries, 0 to 391056
Data columns (total 28 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   video_id                                  391057 non-null  str
 1   title                                     391057 non-null  str
 2   publishedAt                               391057 non-null  str
 3   channelId                                 391057 non-null  str
 4   channelTitle                              391057 non-null  str
 5   categoryId                                391057 non-null  object
 6   trending_date                             172695 non-null  str
 7   tags                                      269673 non-null  object
 8   view_count                                391035 non-null  object
 9   likes                                     390907 non-null  object
 10  comment_count                             391021 non-null  object
 11  thumbnail_link                            391057 non-null  str
 12  comments_disabled                         390043 non-null  float64
 13  description                               331757 non-null  str
 14  is_trending                               391057 non-null  int64
 15  defaultLanguage                           375875 non-null  str
 16  duration                                  375866 non-null  str
 17  dimension                                 375875 non-null  str
 18  definition                                375875 non-null  str
 19  caption                                   375875 non-null  str
 20  licensedContent                           375875 non-null  object
 21  projection                                375875 non-null  str
 22  embeddable                                375875 non-null  object
 23  madeForKids                               375875 non-null  object
 24  favoriteCount                             375875 non-null  str
 25  contentDetails.regionRestriction.blocked  19039 non-null   object
 26  contentDetails.regionRestriction.allowed  14192 non-null   object
 27  contentDetails.contentRating.ytRating     505 non-null     object
dtypes: float64(1), int64(1), object(11), str(15)
memory usage: 83.5+ MB

In [249]:
final_df.to_csv('/Users/ziadsamer/Documents/who-will-viral/data/youtube/final_youtube_dataset.csv', index=False)